name: Deploy

on:
  push:
    branches:
      - main
    
jobs:
  deploy:
    runs-on: self-hosted
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Create root env file
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_POSTGRES_USER: ${{secrets.POSTGRES_USER}}
          envkey_POSTGRES_PORT: ${{secrets.POSTGRES_PORT}}
          envkey_POSTGRES_HOST: ${{secrets.POSTGRES_HOST}}
          envkey_POSTGRES_PASSWORD: ${{secrets.POSTGRES_PASSWORD}}
          envkey_POSTGRES_DB: ${{secrets.POSTGRES_DB}}
          envkey_API_PORT: ${{secrets.API_PORT}}
          envkey_API_URL: ${{secrets.API_URL}}
          envkey_CLIENT_URL: ${{secrets.CLIENT_URL}}
          envkey_DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
          directory: ./
          file_name: .env
          fail_on_empty: true
      - name: Run
        run: docker compose down && docker compose pull && docker compose up -d
