name: Build and deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Create client env file
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_NEXT_PUBLIC_DEV_API_URL: ${{secrets.NEXT_PUBLIC_DEV_API_URL}}
          envkey_NEXT_PUBLIC_PROD_API_URL: ${{secrets.NEXT_PUBLIC_PROD_API_URL}}
          envkey_NEXT_PUBLIC_FIREBASE_API_KEY: ${{secrets.NEXT_PUBLIC_FIREBASE_API_KEY}}
          envkey_NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: ${{secrets.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN}}
          envkey_NEXT_PUBLIC_FIREBASE_PROJECT_ID: ${{secrets.NEXT_PUBLIC_FIREBASE_PROJECT_ID}}
          envkey_NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: ${{secrets.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET}}
          envkey_NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: ${{secrets.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID}}
          envkey_NEXT_PUBLIC_FIREBASE_APP_ID: ${{secrets.NEXT_PUBLIC_FIREBASE_APP_ID}}
          envkey_NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID: ${{secrets.NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID}}
          directory: client
          file_name: .env
          fail_on_empty: true
      - name: Create root env file
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_POSTGRES_USER: ${{secrets.POSTGRES_USER}}
          envkey_POSTGRES_PORT: ${{secrets.POSTGRES_PORT}}
          envkey_POSTGRES_HOST: ${{secrets.POSTGRES_HOST}}
          envkey_POSTGRES_PASSWORD: ${{secrets.POSTGRES_PASSWORD}}
          envkey_POSTGRES_DB: ${{secrets.POSTGRES_DB}}
          envkey_API_PORT: ${{secrets.API_PORT}}
          envkey_API_URL: ${{secrets.API_URL}}
          envkey_CLIENT_URL: ${{secrets.CLIENT_URL}}
          envkey_DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
          envkey_API_BUILD_TARGET: ${{secrets.API_BUILD_TARGET}}
          directory: ./
          file_name: .env
          fail_on_empty: true
      - name: Build
        run: docker compose build
      - name: Run
        run: docker compose down && docker compose up -d
